### ISSUE TITLE
Invalid RSS feed

### ISSUE THREAD

**Issue by rEnr3n** [ArchStrike/ArchStrike-Website#6]
Your rss feed for the news is invalid.

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Farchstrike.org%2Frss%2Fnews

**Comment by Cthulu201** [comment]
Looks like a bug with the validator; entity is valid per W3C:

https://www.w3.org/wiki/Common_HTML_entities_used_for_typography


R,
Mike

-----Original Message-----

**Comment by xorond** [comment]
closing
